
###

GET http://localhost:3333/pontoDeColeta


###

POST http://localhost:3333/pontoDeColeta
Content-Type: application/json

{
    "name": "praia lalalfsdal",
    "endereco": "rua sao jorge ",
    "complemento": "casa 02",
    "descricao": "o kok o ko ko k o"

    
}

###

PUT http://localhost:3333/pontoDeColeta/ae14c592-c367-48d1-8e24-7f808b058c88
Content-Type: application/json

{ 
    "name": "dasdsad lalalfsdal",
    "endereco": "rdadsada sao jorge ",
    "complemento": "casasdsad 02",
    "descricao": "o kok dasdao ko ko k o"
}

###

DELETE http://localhost:3333/pontoDeColeta



### user

GET http://localhost:3333/users

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "",
    "password": ""
}

###

PUT http://localhost:3333/users/id
Content-Type: application/json

{
    "name": "",
    "password": ""
}

###

DELETE http://localhost:3333/users/id