
###

GET http://localhost:3333/pontoDeColeta


###

POST http://localhost:3333/pontoDeColeta
Content-Type: application/json

{
    "name": "praia lalalfsdal",
    "endereco": "rua sao jorge ",
    "complemento": "casa 02",
    "descricao": "o kok o ko ko k o"

    
}

###

PUT http://localhost:3333/pontoDeColeta/2d21f6c8-19c4-47d4-a704-21f9cf12e103
Content-Type: application/json

{ 
    "name": "titicia lalalfsdal",
    "endereco": "rdadsada sao jorge ",
    "complemento": "casasdsad 02",
    "descricao": "o kok dasdao ko ko k o"
}

###

DELETE http://localhost:3333/pontoDeColeta/63e2c4be-97a8-4930-93f4-a6d1cb53128c



### user

GET http://localhost:3333/users

###

POST http://localhost:3333/users
Content-Type: application/json

{
    "name": "",
    "password": ""
}

###

PUT http://localhost:3333/users/id
Content-Type: application/json

{
    "name": "",
    "password": ""
}

###

DELETE http://localhost:3333/users/id